# Generated by Django 4.1.1 on 2022-10-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=128, verbose_name='Hostname')),
                ('ip', models.CharField(max_length=128, verbose_name='IP')),
                ('port', models.IntegerField(default=22, verbose_name='Port')),
            ],
        ),
    ]
