# Generated by Django 4.1.9 on 2023-06-05 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=128, verbose_name='Hostname')),
                ('ip', models.CharField(max_length=128, verbose_name='IP')),
                ('port', models.IntegerField(default=22, verbose_name='Port')),
            ],
        ),
        migrations.CreateModel(
            name='DBInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='实例名称')),
                ('provider', models.IntegerField(choices=[(0, 'Self-Host'), (1, 'Aliyun')], default=1, verbose_name='提供商')),
                ('instance_id', models.CharField(blank=True, max_length=128, null=True)),
                ('instance_class', models.CharField(blank=True, max_length=128, null=True)),
                ('instance_type', models.IntegerField(choices=[(0, 'Primary'), (1, 'Readonly'), (2, 'Guard'), (3, 'Temp')], default=0, verbose_name='实例类型')),
                ('engine', models.IntegerField(choices=[(0, 'MySQL'), (1, 'PolarDB'), (2, 'MariaDB'), (3, 'SQLServer'), (4, 'PostgreSQL')], default=0, verbose_name='数据库引擎')),
                ('version', models.CharField(blank=True, default='', max_length=32, verbose_name='数据库版本')),
                ('host', models.CharField(blank=True, max_length=255, verbose_name='数据库链接')),
                ('port', models.IntegerField(default=3306, verbose_name='数据库端口')),
                ('username', models.CharField(blank=True, max_length=128, verbose_name='超管账号')),
                ('password', models.CharField(blank=True, max_length=128, verbose_name='超管密码')),
                ('status', models.IntegerField(choices=[(0, 'RUNNING'), (1, 'STOPPED'), (2, 'OFFLINE')], default=2, verbose_name='服务状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '数据库实例实体表',
                'verbose_name_plural': '数据库实例实体表',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='数据库名称')),
                ('desc', models.TextField(blank=True, default='', verbose_name='描述信息')),
                ('charset', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('db_instance', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='databases', to='myapp.dbinstance')),
            ],
            options={
                'verbose_name': '数据库实体表',
                'verbose_name_plural': '数据库实体表',
                'ordering': ['-pk'],
            },
        ),
    ]
